
import os
from PIL import Image
# open an image file (.bmp,.jpg,.png,.gif) you have in the working folder
imageFile = "zFlowers.jpg"
path = 'Tudor'

imgPaths = [os.path.join(path,f) for f in os.listdir(path)]

for imgPath in imgPaths:
	pil=Image.open(imgPath).convert('L')
	print(imgPath)
        
        pathSplit = os.path.split(imgPath)[-1].split("/")
            
        pil=pil.resize((200,200), Image.ANTIALIAS)
	#pil.save()
	print(str(pathSplit[0]))
	ext = ".jpg"
	pil.save(str(pathSplit[0]))
# image viewer  i_view32.exe   free download from:  http://www.irfanview.com/
# avoids the many huge bitmap files generated by PIL's show()

